version: 2

models:
#DQ Check for Aisles table
  - name: stg_insta_aisles_grp6
    description: "no nulls or empty values"
    columns:
      - name: aisle
        description: "Name of aisle"
        tests:
          - not_null
      - name: aisle_id
        description: "Unique identifier for each aisle"
        tests:
          - not_null
          - unique

#DQ Check for Department Table
  - name: stg_insta_department_grp6
    description: "no nulls or empty values"
    columns:
      - name: department
        description: "Name of department"
        tests:
          - not_null
      - name: department_id
        description: "Unique identifier for each department"
        tests:
          - not_null
          - unique

#DQ Check for Product Order Table
# - name: stg_insta_order_products_grp6
#    description: "Order and Product Table"
#    columns:
#      - name: product_id
#        description: "No nulls for product ID"
#        tests:
#          - not_null
#      - name: order_id
#        description: "No nulls for order ID"
#        tests:
#          - not null

#    tests:
#      - dbt_utils.unique_combination_of_columns:
#          combination_of_columns:
#            - order_id
#            - product_id

      
          

#DQ Check for Order Table
  - name: stg_insta_orders_grp6
    description: "no nulls or empty values"
    columns:
      - name: order_id
        description: "Unique identifier for each Order"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "No nulls or empty values for user ID"
        tests:
          - not_null

#DQ Check for Products table
  - name: stg_insta_products_grp6
    description: "Cleaned product data"
    columns:
      - name: product_id
        description: "Unique ID for each product"
        tests:
          - not_null
          - unique
      - name: aisle_id
        description: "FK to aisles table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_insta_aisles_grp6')
              field: aisle_id
      - name: department_id
        description: "FK to departments table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_insta_department_grp6')
              field: department_id

#Checking Referential integrity check
  - name: stg_insta_order_products_grp6
    description: "Mapping table between orders and products"

    columns:
      - name: order_id
        description: "Unique order ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_insta_orders_grp6')   # parent table
              field: order_id                    # matching column in parent table

      - name: product_id
        description: "Unique product ID"
        tests:
          - not_null
          - relationships:
              to: ref('stg_insta_products_grp6')  # parent table
              field: product_id                   # matching column in parent table


      